# Generated by Django 5.2.3 on 2025-10-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
